# Use postgres/example user/password credentials
version: '3.1'

services:
  php:
    image: php:7.4-apache
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    volumes:
      - pg:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
volumes:
  db:
  pg:
