# Use postgres/example user/password credentials
version: '3.1'

services:
  php:
    build: 
      context: ./docker
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./:/var/www/
      - ./data:/var/www/data
    user: 1000:1000
    ports:
      - 8080:80
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8081:80
    volumes:
      - pg:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
volumes:
  pg:
