# Use postgres/example user/password credentials
version: '3.1'

services:
  php:
    build: 
      context: ./docker
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./:/var/www/
    ports:
      - 8080:80
volumes:
  pg:
