@startuml

skinparam Monochrome true

title Profile Modification

|#bcbcbc|User|
|#d0d0d0|Backend|
|#dddddd|Database|

|User|
start
    :Acede à pagina de perfil;
    :Modifica o utilizador;
    |Backend|
    :Verifica as permissões e \nmodifica o utilizador;
    |Database|
    :Modifica o utilizador;
stop

@enduml