@startuml

skinparam Monochrome true

title Delete Permanently

|#bcbcbc|User|
|#d0d0d0|Backend|
|#dddddd|Database|

|User|
start
    :Acede à pagina da reciclagem;
    :Elimina o ficheiro \nda reciclagem;
    |Backend|
    :Verifica as permissões e \nelimina o ficheiro \npermanentemente;
    |Database|
    :Elimina o ficheiro;
stop

