@startuml

skinparam Monochrome true

title File Modification

|#bcbcbc|User|
|#d0d0d0|Backend|
|#dddddd|Database|

|User|
start
    :Acede à pagina de ficheiros;
    :Modifica o ficheiro;
    |Backend|
    :Verifica as permissões e \nmodifica o ficheiro;
    |Database|
    :modifica o ficheiro;
stop


@enduml